apiVersion: v1
kind: Service
metadata:
  name: 'postgres'
  labels:
     app: 'postgres'
  namespace: '{{ .Values.POSTGRES_NS }}'
spec:
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: http-db
#      protocol: TCP
      name: port-12
  selector:
      app: postgres
