---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  namespace: '{{ .Release.Namespace }}'
spec:
  replicas: 2
  selector:
    matchLabels:
        app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: my-web
          image: '{{ .Values.IMAGE_WEB }}:{{ $.Chart.AppVersion }}'
          imagePullPolicy: "Always"
          ports:
            - containerPort: {{ .Values.PORT }}
              name: http-web
          envFrom:
            - configMapRef:
                name: 'web-config'
      imagePullSecrets:
         - name: regcred
