---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: '{{ .Release.Namespace }}'
spec:
  replicas: 2
  selector:
    matchLabels:
        app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: my-api
          image: '{{ .Values.IMAGE_API }}:{{ $.Chart.AppVersion }}'
          imagePullPolicy: "Always"
          ports:
            - containerPort: {{ .Values.PORT }}
              name: http-api
          envFrom:
            - configMapRef:
                name: 'api-config'
      imagePullSecrets:
         - name: regcred
