apiVersion: v1
kind: Service
metadata:
  name: 'api'
  labels:
     app: 'api'
  namespace: '{{ .Release.Namespace }}'
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.PORT }}
      targetPort: http-api
  selector:
      app: api
